/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
  '/api/v1/system/status': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** Read public control-plane compatibility status */
    get: {
      parameters: {
        query?: never;
        header?: never;
        path?: never;
        cookie?: never;
      };
      requestBody?: never;
      responses: {
        /** @description Control-plane status */
        200: {
          headers: {
            /** @description Request correlation identifier */
            'X-Request-Id': string;
            [name: string]: unknown;
          };
          content: {
            'application/json': components['schemas']['SystemStatus'];
          };
        };
        /** @description Unexpected server error */
        500: {
          headers: {
            /** @description Request correlation identifier */
            'X-Request-Id': string;
            [name: string]: unknown;
          };
          content: {
            'application/json': components['schemas']['ErrorResponse'];
          };
        };
      };
    };
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/api/v1/auth/setup/status': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** Read first-run setup state */
    get: operations['getSetupStatus'];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/api/v1/auth/setup': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /** Create the only administrator */
    post: operations['setupAdmin'];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/api/v1/auth/login': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /** Start an administrator browser session */
    post: operations['loginAdmin'];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/api/v1/auth/refresh': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /** Rotate the administrator refresh session */
    post: operations['refreshAdminSession'];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/api/v1/auth/logout': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /** End the administrator browser session */
    post: operations['logoutAdmin'];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/api/v1/auth/me': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** Read the authenticated administrator */
    get: operations['getCurrentAdmin'];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
}
export type webhooks = Record<string, never>;
export interface components {
  schemas: {
    CursorQuery: {
      cursor?: string;
      /** @default 50 */
      limit: number;
    };
    CursorPage: {
      nextCursor: string | null;
    };
    SystemStatus: {
      /** @enum {string} */
      name: 'wg-easy-plane';
      version: string;
      /** @enum {string} */
      apiVersion: 'v1';
      /** @enum {string} */
      supportedWgEasyVersion: '15.4.0';
    };
    ErrorResponse: {
      error: {
        code: components['schemas']['ErrorCode'];
        message: string;
        details?: {
          [key: string]: unknown;
        };
        /** Format: uuid */
        requestId: string;
      };
    };
    /** @enum {string} */
    ErrorCode:
      | 'BAD_REQUEST'
      | 'UNAUTHORIZED'
      | 'FORBIDDEN'
      | 'NOT_FOUND'
      | 'CONFLICT'
      | 'VALIDATION_ERROR'
      | 'RATE_LIMITED'
      | 'UPSTREAM_ERROR'
      | 'INTERNAL_ERROR';
    SetupStatus: {
      setupRequired: boolean;
    };
    AuthenticatedAdmin: {
      admin: components['schemas']['PublicAdmin'];
    };
    PublicAdmin: {
      /** Format: uuid */
      id: string;
      /**
       * @description Lowercase administrator username
       * @example panel-admin
       */
      username: string;
    };
    SetupRequest: {
      /**
       * @description Lowercase administrator username
       * @example panel-admin
       */
      username: string;
      /** @description Administrator password; never returned by the API */
      password: string;
    };
    LoginRequest: {
      username: string;
      password: string;
    };
  };
  responses: never;
  parameters: never;
  requestBodies: never;
  headers: never;
  pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
  getSetupStatus: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Current setup state */
      200: {
        headers: {
          /** @description Request correlation identifier */
          'X-Request-Id': string;
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['SetupStatus'];
        };
      };
      /** @description Unexpected server error */
      500: {
        headers: {
          /** @description Request correlation identifier */
          'X-Request-Id': string;
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['ErrorResponse'];
        };
      };
    };
  };
  setupAdmin: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody: {
      content: {
        'application/json': components['schemas']['SetupRequest'];
      };
    };
    responses: {
      /** @description Administrator created */
      201: {
        headers: {
          /** @description Request correlation identifier */
          'X-Request-Id': string;
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['AuthenticatedAdmin'];
        };
      };
      /** @description Invalid setup request */
      400: {
        headers: {
          /** @description Request correlation identifier */
          'X-Request-Id': string;
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['ErrorResponse'];
        };
      };
      /** @description Untrusted request origin */
      403: {
        headers: {
          /** @description Request correlation identifier */
          'X-Request-Id': string;
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['ErrorResponse'];
        };
      };
      /** @description Administrator setup is already complete */
      409: {
        headers: {
          /** @description Request correlation identifier */
          'X-Request-Id': string;
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['ErrorResponse'];
        };
      };
      /** @description Authentication attempt limit exceeded */
      429: {
        headers: {
          /** @description Request correlation identifier */
          'X-Request-Id': string;
          /** @description Seconds until another attempt is allowed */
          'Retry-After': string;
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['ErrorResponse'];
        };
      };
      /** @description Unexpected server error */
      500: {
        headers: {
          /** @description Request correlation identifier */
          'X-Request-Id': string;
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['ErrorResponse'];
        };
      };
    };
  };
  loginAdmin: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody: {
      content: {
        'application/json': components['schemas']['LoginRequest'];
      };
    };
    responses: {
      /** @description Administrator authenticated */
      200: {
        headers: {
          /** @description Request correlation identifier */
          'X-Request-Id': string;
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['AuthenticatedAdmin'];
        };
      };
      /** @description Invalid login request */
      400: {
        headers: {
          /** @description Request correlation identifier */
          'X-Request-Id': string;
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['ErrorResponse'];
        };
      };
      /** @description Invalid username or password */
      401: {
        headers: {
          /** @description Request correlation identifier */
          'X-Request-Id': string;
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['ErrorResponse'];
        };
      };
      /** @description Untrusted request origin */
      403: {
        headers: {
          /** @description Request correlation identifier */
          'X-Request-Id': string;
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['ErrorResponse'];
        };
      };
      /** @description Authentication attempt limit exceeded */
      429: {
        headers: {
          /** @description Request correlation identifier */
          'X-Request-Id': string;
          /** @description Seconds until another attempt is allowed */
          'Retry-After': string;
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['ErrorResponse'];
        };
      };
      /** @description Unexpected server error */
      500: {
        headers: {
          /** @description Request correlation identifier */
          'X-Request-Id': string;
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['ErrorResponse'];
        };
      };
    };
  };
  refreshAdminSession: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Session rotated */
      204: {
        headers: {
          /** @description Request correlation identifier */
          'X-Request-Id': string;
          [name: string]: unknown;
        };
        content?: never;
      };
      /** @description Refresh session is invalid or has been reused */
      401: {
        headers: {
          /** @description Request correlation identifier */
          'X-Request-Id': string;
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['ErrorResponse'];
        };
      };
      /** @description Untrusted request origin */
      403: {
        headers: {
          /** @description Request correlation identifier */
          'X-Request-Id': string;
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['ErrorResponse'];
        };
      };
      /** @description Authentication attempt limit exceeded */
      429: {
        headers: {
          /** @description Request correlation identifier */
          'X-Request-Id': string;
          /** @description Seconds until another attempt is allowed */
          'Retry-After': string;
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['ErrorResponse'];
        };
      };
      /** @description Unexpected server error */
      500: {
        headers: {
          /** @description Request correlation identifier */
          'X-Request-Id': string;
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['ErrorResponse'];
        };
      };
    };
  };
  logoutAdmin: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Cookies cleared and identifiable session revoked */
      204: {
        headers: {
          /** @description Request correlation identifier */
          'X-Request-Id': string;
          [name: string]: unknown;
        };
        content?: never;
      };
      /** @description Untrusted request origin */
      403: {
        headers: {
          /** @description Request correlation identifier */
          'X-Request-Id': string;
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['ErrorResponse'];
        };
      };
      /** @description Unexpected server error */
      500: {
        headers: {
          /** @description Request correlation identifier */
          'X-Request-Id': string;
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['ErrorResponse'];
        };
      };
    };
  };
  getCurrentAdmin: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Current administrator */
      200: {
        headers: {
          /** @description Request correlation identifier */
          'X-Request-Id': string;
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['AuthenticatedAdmin'];
        };
      };
      /** @description Authentication is required */
      401: {
        headers: {
          /** @description Request correlation identifier */
          'X-Request-Id': string;
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['ErrorResponse'];
        };
      };
      /** @description Unexpected server error */
      500: {
        headers: {
          /** @description Request correlation identifier */
          'X-Request-Id': string;
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['ErrorResponse'];
        };
      };
    };
  };
}
