/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
  '/api/v1/system/status': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** Read public control-plane compatibility status */
    get: {
      parameters: {
        query?: never;
        header?: never;
        path?: never;
        cookie?: never;
      };
      requestBody?: never;
      responses: {
        /** @description Control-plane status */
        200: {
          headers: {
            /** @description Request correlation identifier */
            'X-Request-Id': string;
            [name: string]: unknown;
          };
          content: {
            'application/json': components['schemas']['SystemStatus'];
          };
        };
        /** @description Unexpected server error */
        500: {
          headers: {
            /** @description Request correlation identifier */
            'X-Request-Id': string;
            [name: string]: unknown;
          };
          content: {
            'application/json': components['schemas']['ErrorResponse'];
          };
        };
      };
    };
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
}
export type webhooks = Record<string, never>;
export interface components {
  schemas: {
    CursorQuery: {
      cursor?: string;
      /** @default 50 */
      limit: number;
    };
    CursorPage: {
      nextCursor: string | null;
    };
    SystemStatus: {
      /** @enum {string} */
      name: 'wg-easy-plane';
      version: string;
      /** @enum {string} */
      apiVersion: 'v1';
      /** @enum {string} */
      supportedWgEasyVersion: '15.4.0';
    };
    ErrorResponse: {
      error: {
        code: components['schemas']['ErrorCode'];
        message: string;
        details?: {
          [key: string]: unknown;
        };
        /** Format: uuid */
        requestId: string;
      };
    };
    /** @enum {string} */
    ErrorCode:
      | 'BAD_REQUEST'
      | 'UNAUTHORIZED'
      | 'FORBIDDEN'
      | 'NOT_FOUND'
      | 'CONFLICT'
      | 'VALIDATION_ERROR'
      | 'RATE_LIMITED'
      | 'UPSTREAM_ERROR'
      | 'INTERNAL_ERROR';
  };
  responses: never;
  parameters: never;
  requestBodies: never;
  headers: never;
  pathItems: never;
}
export type $defs = Record<string, never>;
export type operations = Record<string, never>;
