/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
  '/api/v1/system/status': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** Read public control-plane compatibility status */
    get: {
      parameters: {
        query?: never;
        header?: never;
        path?: never;
        cookie?: never;
      };
      requestBody?: never;
      responses: {
        /** @description Control-plane status */
        200: {
          headers: {
            /** @description Request correlation identifier */
            'X-Request-Id': string;
            [name: string]: unknown;
          };
          content: {
            'application/json': components['schemas']['SystemStatus'];
          };
        };
        /** @description Unexpected server error */
        500: {
          headers: {
            /** @description Request correlation identifier */
            'X-Request-Id': string;
            [name: string]: unknown;
          };
          content: {
            'application/json': components['schemas']['ErrorResponse'];
          };
        };
      };
    };
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/api/v1/auth/setup/status': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** Read first-run setup state */
    get: operations['getSetupStatus'];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/api/v1/auth/setup': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /** Create the only administrator */
    post: operations['setupAdmin'];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/api/v1/auth/login': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /** Start an administrator browser session */
    post: operations['loginAdmin'];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/api/v1/auth/refresh': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /** Rotate the administrator refresh session */
    post: operations['refreshAdminSession'];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/api/v1/auth/logout': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /** End the administrator browser session */
    post: operations['logoutAdmin'];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/api/v1/auth/me': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** Read the authenticated administrator */
    get: operations['getCurrentAdmin'];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/api/v1/tokens': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** List safe API token metadata */
    get: operations['listApiTokens'];
    put?: never;
    /** Create an API token and reveal its secret once */
    post: operations['createApiToken'];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/api/v1/tokens/{tokenId}': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    post?: never;
    /** Revoke an API token */
    delete: operations['revokeApiToken'];
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/api/v1/nodes': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** List safe node metadata */
    get: operations['listNodes'];
    put?: never;
    /** Create and probe a node */
    post: operations['createNode'];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/api/v1/nodes/test': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /** Test unsaved node connection settings */
    post: operations['testNodeConnection'];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/api/v1/nodes/{nodeId}': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** Read safe node metadata */
    get: operations['getNode'];
    put?: never;
    post?: never;
    /** Delete a node without upstream side effects */
    delete: operations['deleteNode'];
    options?: never;
    head?: never;
    /** Update and conditionally probe a node */
    patch: operations['updateNode'];
    trace?: never;
  };
  '/api/v1/nodes/{nodeId}/test': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /** Retest a stored node */
    post: operations['testStoredNode'];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/api/v1/nodes/{nodeId}/sync': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /** Synchronize one node client inventory */
    post: operations['syncNode'];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/api/v1/clients/discovered': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** List read-only clients discovered on nodes */
    get: operations['listDiscoveredClients'];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
}
export type webhooks = Record<string, never>;
export interface components {
  schemas: {
    CursorQuery: {
      cursor?: string;
      /** @default 50 */
      limit: number;
    };
    CursorPage: {
      nextCursor: string | null;
    };
    SystemStatus: {
      /** @enum {string} */
      name: 'wg-easy-plane';
      version: string;
      /** @enum {string} */
      apiVersion: 'v1';
      /** @enum {string} */
      supportedWgEasyVersion: '15.4.0';
    };
    ErrorResponse: {
      error: {
        code: components['schemas']['ErrorCode'];
        message: string;
        details?: {
          [key: string]: unknown;
        };
        /** Format: uuid */
        requestId: string;
      };
    };
    /** @enum {string} */
    ErrorCode:
      | 'BAD_REQUEST'
      | 'UNAUTHORIZED'
      | 'FORBIDDEN'
      | 'NOT_FOUND'
      | 'CONFLICT'
      | 'VALIDATION_ERROR'
      | 'RATE_LIMITED'
      | 'UPSTREAM_ERROR'
      | 'INTERNAL_ERROR';
    SetupStatus: {
      setupRequired: boolean;
    };
    AuthenticatedAdmin: {
      admin: components['schemas']['PublicAdmin'];
    };
    PublicAdmin: {
      /** Format: uuid */
      id: string;
      /**
       * @description Lowercase administrator username
       * @example panel-admin
       */
      username: string;
    };
    SetupRequest: {
      /**
       * @description Lowercase administrator username
       * @example panel-admin
       */
      username: string;
      /** @description Administrator password; never returned by the API */
      password: string;
    };
    LoginRequest: {
      username: string;
      password: string;
    };
    ApiTokenList: {
      items: components['schemas']['ApiTokenMetadata'][];
      page: components['schemas']['CursorPage'];
    };
    ApiTokenMetadata: {
      /** Format: uuid */
      id: string;
      name: string;
      prefix: string;
      scopes: components['schemas']['ApiTokenScope'][];
      /** Format: date-time */
      createdAt: string;
      /** Format: date-time */
      expiresAt: string | null;
      /** Format: date-time */
      lastUsedAt: string | null;
      /** Format: date-time */
      revokedAt: string | null;
    };
    /** @enum {string} */
    ApiTokenScope:
      | 'system:read'
      | 'nodes:read'
      | 'nodes:write'
      | 'clients:read'
      | 'clients:write'
      | 'subscriptions:read'
      | 'subscriptions:write'
      | 'tokens:manage';
    CreatedApiToken: {
      token: string;
      metadata: components['schemas']['ApiTokenMetadata'];
    };
    CreateApiTokenRequest: {
      name: string;
      scopes: components['schemas']['ApiTokenScope'][];
      /** Format: date-time */
      expiresAt?: string | null;
    };
    NodeList: {
      items: components['schemas']['NodeMetadata'][];
      page: components['schemas']['CursorPage'];
    };
    NodeMetadata: {
      /** Format: uuid */
      id: string;
      name: string;
      protocol: components['schemas']['NodeProtocol'];
      host: components['schemas']['NodeHost'];
      port: number;
      allowInsecureTls: boolean;
      status: components['schemas']['NodeStatus'];
      detectedVersion: string | null;
      mode: components['schemas']['NodeMode'];
      lastErrorCode: components['schemas']['NodeErrorCode'];
      /** Format: date-time */
      lastCheckedAt: string | null;
      /** Format: date-time */
      lastSyncedAt: string | null;
      /** Format: date-time */
      createdAt: string;
      /** Format: date-time */
      updatedAt: string;
    };
    /** @enum {string} */
    NodeProtocol: 'http' | 'https';
    /**
     * @description Hostname or IP address without a scheme, path, or port
     * @example node.example.test
     */
    NodeHost: string;
    /** @enum {string} */
    NodeStatus:
      | 'healthy'
      | 'unreachable'
      | 'auth_failed'
      | 'tls_error'
      | 'unsupported_version'
      | 'api_incompatible';
    /** @enum {string|null} */
    NodeMode: 'wireguard' | 'amnezia' | null;
    /** @enum {string|null} */
    NodeErrorCode:
      | 'TIMEOUT'
      | 'TLS_ERROR'
      | 'UNREACHABLE'
      | 'REDIRECT_BLOCKED'
      | 'RESPONSE_TOO_LARGE'
      | 'AUTH_FAILED'
      | 'NOT_FOUND'
      | 'UNSUPPORTED_VERSION'
      | 'API_INCOMPATIBLE'
      | 'UPSTREAM_ERROR'
      | null;
    CreateNodeRequest: {
      protocol: components['schemas']['NodeProtocol'];
      host: components['schemas']['NodeHost'];
      port: number;
      username: string;
      password: string;
      /** @default false */
      allowInsecureTls: boolean;
      name: string;
    };
    NodeConnectionTestResult: {
      status: components['schemas']['NodeStatus'];
      detectedVersion: string | null;
      mode: components['schemas']['NodeMode'];
      lastErrorCode: components['schemas']['NodeErrorCode'];
      /** Format: date-time */
      lastCheckedAt: string;
    };
    TestNodeConnectionRequest: {
      protocol: components['schemas']['NodeProtocol'];
      host: components['schemas']['NodeHost'];
      port: number;
      username: string;
      password: string;
      /** @default false */
      allowInsecureTls: boolean;
    };
    UpdateNodeRequest: {
      name?: string;
      protocol?: components['schemas']['NodeProtocol'];
      host?: components['schemas']['NodeHost'];
      port?: number;
      username?: string;
      password?: string;
      allowInsecureTls?: boolean;
    };
    SyncRunSummary: {
      /** Format: uuid */
      id: string;
      /** Format: uuid */
      nodeId: string;
      status: components['schemas']['SyncRunStatus'];
      seenCount: number;
      missingCount: number;
      errorCode: components['schemas']['SyncErrorCode'];
      /** Format: date-time */
      startedAt: string;
      /** Format: date-time */
      finishedAt: string;
    };
    /** @enum {string} */
    SyncRunStatus: 'succeeded' | 'failed';
    SyncErrorCode:
      | components['schemas']['NodeErrorCode']
      | ('INTERRUPTED' | 'INTERNAL_ERROR')
      | null;
    DiscoveredClientList: {
      items: components['schemas']['DiscoveredClient'][];
      page: components['schemas']['CursorPage'];
    };
    DiscoveredClient: {
      /** Format: uuid */
      nodeId: string;
      nodeName: string;
      nodeMode: components['schemas']['NodeMode'];
      nodeStatus: components['schemas']['NodeStatus'];
      remoteClientId: number;
      publicData: components['schemas']['DiscoveredClientPublicData'];
      /** @enum {string} */
      upstreamVersion: '15.4.0';
      /** Format: date-time */
      firstSeenAt: string;
      /** Format: date-time */
      lastSeenAt: string;
      /** Format: date-time */
      missingAt: string | null;
    };
    DiscoveredClientPublicData: {
      name: string;
      enabled: boolean;
      /** Format: date-time */
      expiresAt: string | null;
      ipv4Address: string;
      ipv6Address: string;
      /** Format: date-time */
      latestHandshakeAt: string | null;
      transferRx: number | null;
      transferTx: number | null;
      /** Format: date-time */
      createdAt: string;
      /** Format: date-time */
      updatedAt: string;
    };
  };
  responses: never;
  parameters: never;
  requestBodies: never;
  headers: never;
  pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
  getSetupStatus: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Current setup state */
      200: {
        headers: {
          /** @description Request correlation identifier */
          'X-Request-Id': string;
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['SetupStatus'];
        };
      };
      /** @description Unexpected server error */
      500: {
        headers: {
          /** @description Request correlation identifier */
          'X-Request-Id': string;
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['ErrorResponse'];
        };
      };
    };
  };
  setupAdmin: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody: {
      content: {
        'application/json': components['schemas']['SetupRequest'];
      };
    };
    responses: {
      /** @description Administrator created */
      201: {
        headers: {
          /** @description Request correlation identifier */
          'X-Request-Id': string;
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['AuthenticatedAdmin'];
        };
      };
      /** @description Invalid setup request */
      400: {
        headers: {
          /** @description Request correlation identifier */
          'X-Request-Id': string;
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['ErrorResponse'];
        };
      };
      /** @description Untrusted request origin */
      403: {
        headers: {
          /** @description Request correlation identifier */
          'X-Request-Id': string;
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['ErrorResponse'];
        };
      };
      /** @description Administrator setup is already complete */
      409: {
        headers: {
          /** @description Request correlation identifier */
          'X-Request-Id': string;
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['ErrorResponse'];
        };
      };
      /** @description Authentication attempt limit exceeded */
      429: {
        headers: {
          /** @description Request correlation identifier */
          'X-Request-Id': string;
          /** @description Seconds until another attempt is allowed */
          'Retry-After': string;
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['ErrorResponse'];
        };
      };
      /** @description Unexpected server error */
      500: {
        headers: {
          /** @description Request correlation identifier */
          'X-Request-Id': string;
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['ErrorResponse'];
        };
      };
    };
  };
  loginAdmin: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody: {
      content: {
        'application/json': components['schemas']['LoginRequest'];
      };
    };
    responses: {
      /** @description Administrator authenticated */
      200: {
        headers: {
          /** @description Request correlation identifier */
          'X-Request-Id': string;
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['AuthenticatedAdmin'];
        };
      };
      /** @description Invalid login request */
      400: {
        headers: {
          /** @description Request correlation identifier */
          'X-Request-Id': string;
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['ErrorResponse'];
        };
      };
      /** @description Invalid username or password */
      401: {
        headers: {
          /** @description Request correlation identifier */
          'X-Request-Id': string;
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['ErrorResponse'];
        };
      };
      /** @description Untrusted request origin */
      403: {
        headers: {
          /** @description Request correlation identifier */
          'X-Request-Id': string;
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['ErrorResponse'];
        };
      };
      /** @description Authentication attempt limit exceeded */
      429: {
        headers: {
          /** @description Request correlation identifier */
          'X-Request-Id': string;
          /** @description Seconds until another attempt is allowed */
          'Retry-After': string;
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['ErrorResponse'];
        };
      };
      /** @description Unexpected server error */
      500: {
        headers: {
          /** @description Request correlation identifier */
          'X-Request-Id': string;
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['ErrorResponse'];
        };
      };
    };
  };
  refreshAdminSession: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Session rotated */
      204: {
        headers: {
          /** @description Request correlation identifier */
          'X-Request-Id': string;
          [name: string]: unknown;
        };
        content?: never;
      };
      /** @description Refresh session is invalid or has been reused */
      401: {
        headers: {
          /** @description Request correlation identifier */
          'X-Request-Id': string;
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['ErrorResponse'];
        };
      };
      /** @description Untrusted request origin */
      403: {
        headers: {
          /** @description Request correlation identifier */
          'X-Request-Id': string;
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['ErrorResponse'];
        };
      };
      /** @description Authentication attempt limit exceeded */
      429: {
        headers: {
          /** @description Request correlation identifier */
          'X-Request-Id': string;
          /** @description Seconds until another attempt is allowed */
          'Retry-After': string;
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['ErrorResponse'];
        };
      };
      /** @description Unexpected server error */
      500: {
        headers: {
          /** @description Request correlation identifier */
          'X-Request-Id': string;
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['ErrorResponse'];
        };
      };
    };
  };
  logoutAdmin: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Cookies cleared and identifiable session revoked */
      204: {
        headers: {
          /** @description Request correlation identifier */
          'X-Request-Id': string;
          [name: string]: unknown;
        };
        content?: never;
      };
      /** @description Untrusted request origin */
      403: {
        headers: {
          /** @description Request correlation identifier */
          'X-Request-Id': string;
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['ErrorResponse'];
        };
      };
      /** @description Unexpected server error */
      500: {
        headers: {
          /** @description Request correlation identifier */
          'X-Request-Id': string;
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['ErrorResponse'];
        };
      };
    };
  };
  getCurrentAdmin: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Current administrator */
      200: {
        headers: {
          /** @description Request correlation identifier */
          'X-Request-Id': string;
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['AuthenticatedAdmin'];
        };
      };
      /** @description Authentication is required */
      401: {
        headers: {
          /** @description Request correlation identifier */
          'X-Request-Id': string;
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['ErrorResponse'];
        };
      };
      /** @description Unexpected server error */
      500: {
        headers: {
          /** @description Request correlation identifier */
          'X-Request-Id': string;
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['ErrorResponse'];
        };
      };
    };
  };
  listApiTokens: {
    parameters: {
      query?: {
        cursor?: string;
        limit?: number;
      };
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Cursor-paginated token metadata */
      200: {
        headers: {
          /** @description Request correlation identifier */
          'X-Request-Id': string;
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['ApiTokenList'];
        };
      };
      /** @description Invalid pagination cursor or limit */
      400: {
        headers: {
          /** @description Request correlation identifier */
          'X-Request-Id': string;
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['ErrorResponse'];
        };
      };
      /** @description Authentication is required */
      401: {
        headers: {
          /** @description Request correlation identifier */
          'X-Request-Id': string;
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['ErrorResponse'];
        };
      };
      /** @description The credential lacks token-management authority */
      403: {
        headers: {
          /** @description Request correlation identifier */
          'X-Request-Id': string;
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['ErrorResponse'];
        };
      };
      /** @description Unexpected server error */
      500: {
        headers: {
          /** @description Request correlation identifier */
          'X-Request-Id': string;
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['ErrorResponse'];
        };
      };
    };
  };
  createApiToken: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody: {
      content: {
        'application/json': components['schemas']['CreateApiTokenRequest'];
      };
    };
    responses: {
      /** @description API token created */
      201: {
        headers: {
          /** @description Request correlation identifier */
          'X-Request-Id': string;
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['CreatedApiToken'];
        };
      };
      /** @description Invalid API token request */
      400: {
        headers: {
          /** @description Request correlation identifier */
          'X-Request-Id': string;
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['ErrorResponse'];
        };
      };
      /** @description Authentication is required */
      401: {
        headers: {
          /** @description Request correlation identifier */
          'X-Request-Id': string;
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['ErrorResponse'];
        };
      };
      /** @description Untrusted origin or insufficient scope */
      403: {
        headers: {
          /** @description Request correlation identifier */
          'X-Request-Id': string;
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['ErrorResponse'];
        };
      };
      /** @description Unexpected server error */
      500: {
        headers: {
          /** @description Request correlation identifier */
          'X-Request-Id': string;
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['ErrorResponse'];
        };
      };
    };
  };
  revokeApiToken: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        tokenId: string;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Token revoked or already revoked */
      204: {
        headers: {
          /** @description Request correlation identifier */
          'X-Request-Id': string;
          [name: string]: unknown;
        };
        content?: never;
      };
      /** @description Invalid API token identifier */
      400: {
        headers: {
          /** @description Request correlation identifier */
          'X-Request-Id': string;
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['ErrorResponse'];
        };
      };
      /** @description Authentication is required */
      401: {
        headers: {
          /** @description Request correlation identifier */
          'X-Request-Id': string;
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['ErrorResponse'];
        };
      };
      /** @description Untrusted origin or insufficient scope */
      403: {
        headers: {
          /** @description Request correlation identifier */
          'X-Request-Id': string;
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['ErrorResponse'];
        };
      };
      /** @description API token does not exist */
      404: {
        headers: {
          /** @description Request correlation identifier */
          'X-Request-Id': string;
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['ErrorResponse'];
        };
      };
      /** @description Unexpected server error */
      500: {
        headers: {
          /** @description Request correlation identifier */
          'X-Request-Id': string;
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['ErrorResponse'];
        };
      };
    };
  };
  listNodes: {
    parameters: {
      query?: {
        cursor?: string;
        limit?: number;
      };
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Cursor-paginated node metadata */
      200: {
        headers: {
          /** @description Request correlation identifier */
          'X-Request-Id': string;
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['NodeList'];
        };
      };
      /** @description Invalid pagination input */
      400: {
        headers: {
          /** @description Request correlation identifier */
          'X-Request-Id': string;
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['ErrorResponse'];
        };
      };
      /** @description Authentication is required */
      401: {
        headers: {
          /** @description Request correlation identifier */
          'X-Request-Id': string;
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['ErrorResponse'];
        };
      };
      /** @description The credential lacks node-read authority */
      403: {
        headers: {
          /** @description Request correlation identifier */
          'X-Request-Id': string;
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['ErrorResponse'];
        };
      };
      /** @description Unexpected server error */
      500: {
        headers: {
          /** @description Request correlation identifier */
          'X-Request-Id': string;
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['ErrorResponse'];
        };
      };
    };
  };
  createNode: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody: {
      content: {
        'application/json': components['schemas']['CreateNodeRequest'];
      };
    };
    responses: {
      /** @description Node created with safe probe status */
      201: {
        headers: {
          /** @description Request correlation identifier */
          'X-Request-Id': string;
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['NodeMetadata'];
        };
      };
      /** @description Invalid node input */
      400: {
        headers: {
          /** @description Request correlation identifier */
          'X-Request-Id': string;
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['ErrorResponse'];
        };
      };
      /** @description Authentication is required */
      401: {
        headers: {
          /** @description Request correlation identifier */
          'X-Request-Id': string;
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['ErrorResponse'];
        };
      };
      /** @description Untrusted origin or insufficient scope */
      403: {
        headers: {
          /** @description Request correlation identifier */
          'X-Request-Id': string;
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['ErrorResponse'];
        };
      };
      /** @description Node name or endpoint already exists */
      409: {
        headers: {
          /** @description Request correlation identifier */
          'X-Request-Id': string;
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['ErrorResponse'];
        };
      };
      /** @description Unexpected server error */
      500: {
        headers: {
          /** @description Request correlation identifier */
          'X-Request-Id': string;
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['ErrorResponse'];
        };
      };
    };
  };
  testNodeConnection: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody: {
      content: {
        'application/json': components['schemas']['TestNodeConnectionRequest'];
      };
    };
    responses: {
      /** @description Safe probe result */
      200: {
        headers: {
          /** @description Request correlation identifier */
          'X-Request-Id': string;
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['NodeConnectionTestResult'];
        };
      };
      /** @description Invalid node input */
      400: {
        headers: {
          /** @description Request correlation identifier */
          'X-Request-Id': string;
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['ErrorResponse'];
        };
      };
      /** @description Authentication is required */
      401: {
        headers: {
          /** @description Request correlation identifier */
          'X-Request-Id': string;
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['ErrorResponse'];
        };
      };
      /** @description Untrusted origin or insufficient scope */
      403: {
        headers: {
          /** @description Request correlation identifier */
          'X-Request-Id': string;
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['ErrorResponse'];
        };
      };
      /** @description Unexpected server error */
      500: {
        headers: {
          /** @description Request correlation identifier */
          'X-Request-Id': string;
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['ErrorResponse'];
        };
      };
    };
  };
  getNode: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        nodeId: string;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Safe node metadata */
      200: {
        headers: {
          /** @description Request correlation identifier */
          'X-Request-Id': string;
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['NodeMetadata'];
        };
      };
      /** @description Invalid node identifier */
      400: {
        headers: {
          /** @description Request correlation identifier */
          'X-Request-Id': string;
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['ErrorResponse'];
        };
      };
      /** @description Authentication is required */
      401: {
        headers: {
          /** @description Request correlation identifier */
          'X-Request-Id': string;
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['ErrorResponse'];
        };
      };
      /** @description The credential lacks node-read authority */
      403: {
        headers: {
          /** @description Request correlation identifier */
          'X-Request-Id': string;
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['ErrorResponse'];
        };
      };
      /** @description Node does not exist */
      404: {
        headers: {
          /** @description Request correlation identifier */
          'X-Request-Id': string;
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['ErrorResponse'];
        };
      };
      /** @description Unexpected server error */
      500: {
        headers: {
          /** @description Request correlation identifier */
          'X-Request-Id': string;
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['ErrorResponse'];
        };
      };
    };
  };
  deleteNode: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        nodeId: string;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Node deleted */
      204: {
        headers: {
          /** @description Request correlation identifier */
          'X-Request-Id': string;
          [name: string]: unknown;
        };
        content?: never;
      };
      /** @description Invalid node identifier */
      400: {
        headers: {
          /** @description Request correlation identifier */
          'X-Request-Id': string;
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['ErrorResponse'];
        };
      };
      /** @description Authentication is required */
      401: {
        headers: {
          /** @description Request correlation identifier */
          'X-Request-Id': string;
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['ErrorResponse'];
        };
      };
      /** @description Untrusted origin or insufficient scope */
      403: {
        headers: {
          /** @description Request correlation identifier */
          'X-Request-Id': string;
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['ErrorResponse'];
        };
      };
      /** @description Node does not exist */
      404: {
        headers: {
          /** @description Request correlation identifier */
          'X-Request-Id': string;
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['ErrorResponse'];
        };
      };
      /** @description Node has managed placements */
      409: {
        headers: {
          /** @description Request correlation identifier */
          'X-Request-Id': string;
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['ErrorResponse'];
        };
      };
      /** @description Unexpected server error */
      500: {
        headers: {
          /** @description Request correlation identifier */
          'X-Request-Id': string;
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['ErrorResponse'];
        };
      };
    };
  };
  updateNode: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        nodeId: string;
      };
      cookie?: never;
    };
    requestBody: {
      content: {
        'application/json': components['schemas']['UpdateNodeRequest'];
      };
    };
    responses: {
      /** @description Updated safe node metadata */
      200: {
        headers: {
          /** @description Request correlation identifier */
          'X-Request-Id': string;
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['NodeMetadata'];
        };
      };
      /** @description Invalid node input */
      400: {
        headers: {
          /** @description Request correlation identifier */
          'X-Request-Id': string;
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['ErrorResponse'];
        };
      };
      /** @description Authentication is required */
      401: {
        headers: {
          /** @description Request correlation identifier */
          'X-Request-Id': string;
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['ErrorResponse'];
        };
      };
      /** @description Untrusted origin or insufficient scope */
      403: {
        headers: {
          /** @description Request correlation identifier */
          'X-Request-Id': string;
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['ErrorResponse'];
        };
      };
      /** @description Node does not exist */
      404: {
        headers: {
          /** @description Request correlation identifier */
          'X-Request-Id': string;
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['ErrorResponse'];
        };
      };
      /** @description Node name or endpoint already exists */
      409: {
        headers: {
          /** @description Request correlation identifier */
          'X-Request-Id': string;
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['ErrorResponse'];
        };
      };
      /** @description Unexpected server error */
      500: {
        headers: {
          /** @description Request correlation identifier */
          'X-Request-Id': string;
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['ErrorResponse'];
        };
      };
    };
  };
  testStoredNode: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        nodeId: string;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Node metadata with refreshed status */
      200: {
        headers: {
          /** @description Request correlation identifier */
          'X-Request-Id': string;
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['NodeMetadata'];
        };
      };
      /** @description Invalid node identifier */
      400: {
        headers: {
          /** @description Request correlation identifier */
          'X-Request-Id': string;
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['ErrorResponse'];
        };
      };
      /** @description Authentication is required */
      401: {
        headers: {
          /** @description Request correlation identifier */
          'X-Request-Id': string;
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['ErrorResponse'];
        };
      };
      /** @description Untrusted origin or insufficient scope */
      403: {
        headers: {
          /** @description Request correlation identifier */
          'X-Request-Id': string;
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['ErrorResponse'];
        };
      };
      /** @description Node does not exist */
      404: {
        headers: {
          /** @description Request correlation identifier */
          'X-Request-Id': string;
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['ErrorResponse'];
        };
      };
      /** @description Unexpected server error */
      500: {
        headers: {
          /** @description Request correlation identifier */
          'X-Request-Id': string;
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['ErrorResponse'];
        };
      };
    };
  };
  syncNode: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        nodeId: string;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Safe synchronization summary */
      200: {
        headers: {
          /** @description Request correlation identifier */
          'X-Request-Id': string;
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['SyncRunSummary'];
        };
      };
      /** @description Invalid node identifier */
      400: {
        headers: {
          /** @description Request correlation identifier */
          'X-Request-Id': string;
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['ErrorResponse'];
        };
      };
      /** @description Authentication is required */
      401: {
        headers: {
          /** @description Request correlation identifier */
          'X-Request-Id': string;
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['ErrorResponse'];
        };
      };
      /** @description Untrusted origin or insufficient scope */
      403: {
        headers: {
          /** @description Request correlation identifier */
          'X-Request-Id': string;
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['ErrorResponse'];
        };
      };
      /** @description Node does not exist */
      404: {
        headers: {
          /** @description Request correlation identifier */
          'X-Request-Id': string;
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['ErrorResponse'];
        };
      };
      /** @description Node synchronization is already active */
      409: {
        headers: {
          /** @description Request correlation identifier */
          'X-Request-Id': string;
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['ErrorResponse'];
        };
      };
      /** @description Unexpected server error */
      500: {
        headers: {
          /** @description Request correlation identifier */
          'X-Request-Id': string;
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['ErrorResponse'];
        };
      };
    };
  };
  listDiscoveredClients: {
    parameters: {
      query?: {
        cursor?: string;
        limit?: number;
      };
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Cursor-paginated safe discovered-client snapshots */
      200: {
        headers: {
          /** @description Request correlation identifier */
          'X-Request-Id': string;
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['DiscoveredClientList'];
        };
      };
      /** @description Invalid pagination cursor or limit */
      400: {
        headers: {
          /** @description Request correlation identifier */
          'X-Request-Id': string;
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['ErrorResponse'];
        };
      };
      /** @description Authentication is required */
      401: {
        headers: {
          /** @description Request correlation identifier */
          'X-Request-Id': string;
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['ErrorResponse'];
        };
      };
      /** @description The credential lacks client-read authority */
      403: {
        headers: {
          /** @description Request correlation identifier */
          'X-Request-Id': string;
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['ErrorResponse'];
        };
      };
      /** @description Unexpected server error */
      500: {
        headers: {
          /** @description Request correlation identifier */
          'X-Request-Id': string;
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['ErrorResponse'];
        };
      };
    };
  };
}
